"use client";

import React from "react";
import Link from "next/link";
import { Smartphone, Laptop, Download, Eye, FileText, CheckCircle2 } from "lucide-react";

interface ReportItem {
  id: string;
  deviceName: string;
  category: string;
  condition: string;
  aiGrade: string;
  estimatedValue: number;
  repairCost: number;
  status: string;
  createdAt: string;
}

interface RecentReportsProps {
  reports: ReportItem[];
}

export default function RecentReports({ reports }: RecentReportsProps) {
  const handleDownloadPDF = (report: ReportItem) => {
    // Generate simple printable report or trigger PDF alert
    const printContent = `
      =========================================
      REVALUEIQ ENTERPRISE AI DEVICE REPORT
      =========================================
      Device: ${report.deviceName}
      Category: ${report.category}
      Condition: ${report.condition}
      AI Grade: ${report.aiGrade}
      Estimated Value: ₹${report.estimatedValue.toLocaleString("en-IN")}
      Estimated Repair Cost: ₹${report.repairCost.toLocaleString("en-IN")}
      Status: ${report.status}
      Date: ${new Date(report.createdAt).toLocaleDateString()}
      =========================================
      Generated by RevalueIQ AI Valuation Engine 3.0
    `;
    const blob = new Blob([printContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `RevalueIQ_Report_${report.deviceName.replace(/\s+/g, "_")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="font-poppins font-bold text-lg text-white flex items-center gap-2">
            <FileText className="w-5 h-5 text-cyan-400" /> Recent AI Reports
          </h3>
          <p className="text-xs text-slate-400">Detailed AI appraisal logs and condition breakdown</p>
        </div>
      </div>

      <div className="rounded-2xl bg-slate-900/80 border border-slate-800/80 overflow-hidden shadow-xl">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-slate-950/60 border-b border-slate-800 text-[11px] font-bold uppercase tracking-wider text-slate-400">
                <th className="py-3.5 px-4">Device</th>
                <th className="py-3.5 px-4">Condition</th>
                <th className="py-3.5 px-4">AI Grade</th>
                <th className="py-3.5 px-4 text-right">Est. Value</th>
                <th className="py-3.5 px-4 text-right">Repair Cost</th>
                <th className="py-3.5 px-4">Status</th>
                <th className="py-3.5 px-4 text-center">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60 text-xs">
              {reports.map((report) => (
                <tr key={report.id} className="hover:bg-slate-800/50 transition-colors group">
                  {/* Device Info */}
                  <td className="py-3.5 px-4 font-medium">
                    <div className="flex items-center gap-3">
                      <div className="w-9 h-9 rounded-xl bg-cyan-500/10 border border-cyan-500/30 flex items-center justify-center text-cyan-400 shrink-0">
                        {report.category.toLowerCase().includes("laptop") ? (
                          <Laptop className="w-4 h-4" />
                        ) : (
                          <Smartphone className="w-4 h-4" />
                        )}
                      </div>
                      <div>
                        <p className="font-bold text-white group-hover:text-cyan-300 transition-colors">
                          {report.deviceName}
                        </p>
                        <p className="text-[11px] text-slate-400">{report.category}</p>
                      </div>
                    </div>
                  </td>

                  {/* Condition */}
                  <td className="py-3.5 px-4">
                    <span className="inline-flex items-center px-2.5 py-1 rounded-full text-[11px] font-semibold bg-slate-800 text-slate-200 border border-slate-700">
                      {report.condition}
                    </span>
                  </td>

                  {/* AI Grade */}
                  <td className="py-3.5 px-4">
                    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                      Grade {report.aiGrade}
                    </span>
                  </td>

                  {/* Est. Value */}
                  <td className="py-3.5 px-4 text-right font-extrabold text-cyan-400 text-sm">
                    ₹{report.estimatedValue.toLocaleString("en-IN")}
                  </td>

                  {/* Repair Cost */}
                  <td className="py-3.5 px-4 text-right font-semibold text-slate-300">
                    ₹{report.repairCost.toLocaleString("en-IN")}
                  </td>

                  {/* Status */}
                  <td className="py-3.5 px-4">
                    <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-blue-500/10 text-blue-400 border border-blue-500/20">
                      <CheckCircle2 className="w-3 h-3" /> {report.status}
                    </span>
                  </td>

                  {/* Actions */}
                  <td className="py-3.5 px-4 text-center">
                    <div className="flex items-center justify-center gap-2">
                      <Link
                        href={`/dashboard/${report.id}`}
                        className="p-1.5 rounded-lg bg-slate-800 hover:bg-cyan-500/20 hover:text-cyan-400 text-slate-300 transition-colors"
                        title="View Full Report"
                      >
                        <Eye className="w-4 h-4" />
                      </Link>

                      <button
                        type="button"
                        onClick={() => handleDownloadPDF(report)}
                        className="p-1.5 rounded-lg bg-slate-800 hover:bg-blue-500/20 hover:text-blue-400 text-slate-300 transition-colors cursor-pointer"
                        title="Download Summary Report"
                      >
                        <Download className="w-4 h-4" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
