import { AIRecommendationReport, AuthorizedRepairCenter } from "@/types/repairRecommendation";

export const DEFAULT_AI_RECOMMENDATION_REPORT: AIRecommendationReport = {
  id: "REC-90821",
  deviceName: "iPhone 15 Pro",
  deviceCategory: "Smartphone",
  detectedIssues: [
    "Battery Health Low (78% Capacity)",
    "Charging Port Damage (Loose pins)",
    "Screen Minor Hairline Crack",
  ],
  estimatedCostINR: 5800,
  estimatedDays: "2-3 Days",
  confidenceScore: 96,
  rationale: "Repairing this device is 74% more economical than replacing it. Genuine OEM replacement display and battery will extend lifecycle by 3+ years.",
  actionRequired: "Repair Recommended",
};

export const MOCK_AUTHORIZED_CENTERS: AuthorizedRepairCenter[] = [
  {
    id: "center-1",
    name: "Apple Authorized Service Center (F1 Info Solutions)",
    logo: "🍎",
    category: "Authorized",
    rating: 4.8,
    reviewCount: 451,
    status: "Open",
    workingHoursText: "Mon-Sat: 10:00 AM - 9:00 PM",
    distanceKm: 2.1,
    address: "Unit 102, Ground Floor, Cyber Towers, Hitec City",
    city: "Hyderabad",
    area: "Hitec City",
    pincode: "500081",
    phone: "+91 40 4852 9900",
    website: "https://support.apple.com/in-hi/repair",
    lat: 17.4504,
    lng: 78.3809,
    expertise: ["Battery", "Display", "Motherboard", "Camera", "Logic Board"],
    isCertified: true,
    certificationName: "Certified Apple Technician (ACiT)",
    aiTrustScore: 98,
    heroImage: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800",
    photos: [
      "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600",
      "https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=600",
      "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=600",
    ],
    waitingTime: "15-20 mins (With Appointment)",
    repairCharges: [
      { service: "Genuine Display Panel Replacement", priceINR: 3800, warranty: "1 Year Apple Warranty" },
      { service: "High-Capacity OEM Battery Swap", priceINR: 1500, warranty: "1 Year Warranty" },
      { service: "Type-C Charging Port Assembly", priceINR: 900, warranty: "6 Months Warranty" },
      { service: "Ultrasonic Water Decontamination", priceINR: 1200, warranty: "90 Days Warranty" },
    ],
    brandsSupported: ["Apple iPhone", "iPad", "MacBook", "Apple Watch"],
    perks: {
      pickupService: true,
      homeVisit: true,
      parkingAvailable: true,
      accessibility: true,
      nearbyMetro: "Hitec City Metro Station (300 meters)",
      nearbyBusStop: "Cyber Towers Bus Stop (100 meters)",
    },
    aiReviewSummary: {
      overallRating: 4.8,
      reviewCount: 451,
      summaryText: "Customers consistently praise this repair center for genuine spare parts, professional technicians, transparent pricing, and fast turnaround time.",
      strengths: ["Genuine OEM Parts", "Quick 2-Hour Repairs", "Helpful Certified Staff", "Full Warranty Support"],
      weaknesses: ["Slightly expensive diagnostic fee", "Peak hour parking limited"],
    },
    reviews: [
      {
        id: "rev-101",
        userName: "Vikramaditya Rao",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150",
        rating: 5,
        date: "Yesterday",
        reviewText: "Replaced my iPhone 15 Pro screen here. The original Apple display calibration was done flawlessly. Staff was polite and gave me a loaner unit while waiting.",
        helpfulCount: 24,
        ownerResponse: "Thank you Vikramaditya! We strictly use original Apple service parts to ensure TrueTone and FaceID stay 100% operational.",
      },
      {
        id: "rev-102",
        userName: "Priya Sharma",
        avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
        rating: 5,
        date: "3 days ago",
        reviewText: "Quick doorstep pickup service in Gachibowli. Battery changed in 40 minutes and returned same day.",
        helpfulCount: 18,
      },
    ],
  },
  {
    id: "center-2",
    name: "iCare Premium Eco Repair Hub",
    logo: "🛡️",
    category: "Premium Partner",
    rating: 4.9,
    reviewCount: 312,
    status: "Open",
    workingHoursText: "Mon-Sun: 9:30 AM - 8:30 PM",
    distanceKm: 3.4,
    address: "Plot 42, Road No. 36, Jubilee Hills",
    city: "Hyderabad",
    area: "Jubilee Hills",
    pincode: "500033",
    phone: "+91 40 2355 8811",
    website: "https://icare-premium.example.com",
    lat: 17.4319,
    lng: 78.4071,
    expertise: ["Display", "Battery", "Micro-soldering", "Camera", "Water Damage"],
    isCertified: true,
    certificationName: "RevalueIQ Master Eco Technician",
    aiTrustScore: 97,
    heroImage: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800",
    photos: [
      "https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=600",
      "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=600",
    ],
    waitingTime: "10 mins",
    repairCharges: [
      { service: "OLED Display Screen Replacement", priceINR: 3600, warranty: "1 Year Warranty" },
      { service: "High Capacity Battery Replacement", priceINR: 1400, warranty: "18 Months Warranty" },
      { service: "Logic Board Micro-soldering", priceINR: 2200, warranty: "6 Months Warranty" },
    ],
    brandsSupported: ["Apple", "Samsung", "OnePlus", "Google Pixel", "Dell", "HP"],
    perks: {
      pickupService: true,
      homeVisit: true,
      parkingAvailable: true,
      accessibility: true,
      nearbyMetro: "Jubilee Hills Check Post Metro (400 meters)",
      nearbyBusStop: "Road No. 36 Bus stop (150 meters)",
    },
    aiReviewSummary: {
      overallRating: 4.9,
      reviewCount: 312,
      summaryText: "Highest rated eco-certified partner in Jubilee Hills with exceptional micro-soldering expertise and doorstep pickup van.",
      strengths: ["100% Recycled E-Waste Guarantee", "Fast 30-Min Swaps", "Free Pickup & Drop", "Transparent Live Video Diagnostics"],
      weaknesses: ["Weekend walk-ins may require appointment"],
    },
    reviews: [
      {
        id: "rev-103",
        userName: "Anand Verma",
        avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150",
        rating: 5,
        date: "5 days ago",
        reviewText: "Saved ₹18,000 on my laptop logic board repair. Apple store recommended complete board replacement, but iCare replaced just the blown IC chip!",
        helpfulCount: 32,
      },
    ],
  },
  {
    id: "center-3",
    name: "Gachibowli SmartCare Center",
    logo: "🔧",
    category: "Authorized",
    rating: 4.7,
    reviewCount: 198,
    status: "Open",
    workingHoursText: "Mon-Sat: 10:00 AM - 8:00 PM",
    distanceKm: 1.8,
    address: "Opposite DLF Cyber City Gate 2, Gachibowli Main Rd",
    city: "Hyderabad",
    area: "Gachibowli",
    pincode: "500032",
    phone: "+91 40 6677 4433",
    website: "https://gachibowlismartcare.example.com",
    lat: 17.4435,
    lng: 78.3582,
    expertise: ["Battery", "Display", "Charging Port", "Speaker"],
    isCertified: true,
    certificationName: "Authorized Multi-Brand Repair Partner",
    aiTrustScore: 94,
    heroImage: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=800",
    photos: [
      "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=600",
    ],
    waitingTime: "25-30 mins",
    repairCharges: [
      { service: "OLED Screen Repair", priceINR: 3500, warranty: "6 Months Warranty" },
      { service: "Battery Replacement", priceINR: 1300, warranty: "1 Year Warranty" },
    ],
    brandsSupported: ["Apple", "Samsung", "Xiaomi", "Realme", "Vivo"],
    perks: {
      pickupService: true,
      homeVisit: false,
      parkingAvailable: true,
      accessibility: true,
      nearbyMetro: "Raidurg Metro Station (1.2 km)",
      nearbyBusStop: "DLF Cyber City Bus Stop (50 meters)",
    },
    aiReviewSummary: {
      overallRating: 4.7,
      reviewCount: 198,
      summaryText: "Popular among tech workers near DLF Cyber City. Express service with budget friendly genuine spare parts.",
      strengths: ["Convenient DLF Location", "Affordable OEM Prices", "Fast Turnaround"],
      weaknesses: ["No home visit technician"],
    },
    reviews: [
      {
        id: "rev-104",
        userName: "Sneha Reddy",
        avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
        rating: 5,
        date: "1 week ago",
        reviewText: "Walked in during lunch break at DLF. Phone charging port fixed before my break ended!",
        helpfulCount: 15,
      },
    ],
  },
  {
    id: "center-4",
    name: "Madhapur MicroTech Solutions",
    logo: "⚡",
    tagline: "Component Level Logic Repair",
    category: "Premium Partner",
    rating: 4.6,
    reviewCount: 142,
    status: "Open",
    workingHoursText: "Mon-Sat: 10:30 AM - 7:30 PM",
    distanceKm: 4.2,
    address: "Above Union Bank, Inorbit Mall Road, Madhapur",
    city: "Hyderabad",
    area: "Madhapur",
    pincode: "500081",
    phone: "+91 40 4011 2299",
    website: "https://microtechsolutions.example.com",
    lat: 17.4388,
    lng: 78.3901,
    expertise: ["Motherboard", "Water Damage", "Data Recovery"],
    isCertified: true,
    certificationName: "IPC Certified Micro-Soldering Specialist",
    aiTrustScore: 92,
    heroImage: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800",
    photos: ["https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600"],
    waitingTime: "45 mins",
    repairCharges: [
      { service: "Motherboard IC Micro-repair", priceINR: 2800, warranty: "6 Months Warranty" },
      { service: "Water Damage Resuscitation", priceINR: 1800, warranty: "90 Days Warranty" },
    ],
    brandsSupported: ["Apple", "Dell", "Lenovo", "Asus", "Sony"],
    perks: {
      pickupService: true,
      homeVisit: false,
      parkingAvailable: false,
      accessibility: true,
      nearbyMetro: "Madhapur Metro Station (600 meters)",
      nearbyBusStop: "Inorbit Mall Bus Stop (200 meters)",
    },
    aiReviewSummary: {
      overallRating: 4.6,
      reviewCount: 142,
      summaryText: "Specialized in complex motherboard short circuit fixes and liquid damage recovery.",
      strengths: ["Data Recovery Specialists", "Advanced Infrared Soldering"],
      weaknesses: ["Limited car parking on main road"],
    },
    reviews: [
      {
        id: "rev-105",
        userName: "Karthik Subramanian",
        avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150",
        rating: 5,
        date: "2 weeks ago",
        reviewText: "Saved all my code files after a severe water spill. True miracle workers!",
        helpfulCount: 29,
      },
    ],
  },
  {
    id: "center-5",
    name: "Banjara Eco Repair Hub (Express Services)",
    logo: "🌱",
    category: "Unavailable",
    rating: 4.5,
    reviewCount: 88,
    status: "Closed",
    workingHoursText: "Tue-Sun: 11:00 AM - 7:00 PM (Closed Mondays)",
    distanceKm: 6.8,
    address: "Road No. 12, Banjara Hills",
    city: "Hyderabad",
    area: "Banjara Hills",
    pincode: "500034",
    phone: "+91 40 2333 1100",
    website: "https://banjaraecorepair.example.com",
    lat: 17.4156,
    lng: 78.4412,
    expertise: ["Battery", "Display"],
    isCertified: false,
    certificationName: "Eco Certified Recycler",
    aiTrustScore: 88,
    heroImage: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800",
    photos: [],
    waitingTime: "N/A (Closed Today)",
    repairCharges: [
      { service: "Battery Replacement", priceINR: 1500, warranty: "6 Months Warranty" },
    ],
    brandsSupported: ["Apple", "Samsung"],
    perks: {
      pickupService: false,
      homeVisit: false,
      parkingAvailable: true,
      accessibility: true,
      nearbyMetro: "Irrum Manzil Metro (1.5 km)",
      nearbyBusStop: "Banjara Hills Rd 12 Bus stop (100 meters)",
    },
    aiReviewSummary: {
      overallRating: 4.5,
      reviewCount: 88,
      summaryText: "Eco friendly repair shop closed today. Will re-open tomorrow at 11 AM.",
      strengths: ["Great Battery Recycling Program"],
      weaknesses: ["Closed Mondays"],
    },
    reviews: [],
  },
];
