import { RepairShop, RepairShopService, BookingRequest } from "@/types/repairShop";

export const COMMON_REPAIR_CATALOG: RepairShopService[] = [
  {
    id: "serv-screen",
    name: "OLED Screen & Glass Replacement",
    category: "Smartphone",
    price: 129,
    duration: "45-60 mins",
    warranty: "1 Year OEM Warranty",
    ecoSavingsKg: 3.2,
    description: "Full front glass & original OLED display panel replacement with true-tone calibration.",
    popular: true,
  },
  {
    id: "serv-battery",
    name: "High-Capacity Battery Replacement",
    category: "Smartphone",
    price: 69,
    duration: "30 mins",
    warranty: "18 Months Warranty",
    ecoSavingsKg: 1.8,
    description: "Brand new original specification battery replacement with cycle count reset & seal restoration.",
    popular: true,
  },
  {
    id: "serv-water",
    name: "Ultrasonic Water Damage Decontamination",
    category: "Smartphone",
    price: 99,
    duration: "2-4 hrs",
    warranty: "90 Days Guarantee",
    ecoSavingsKg: 4.5,
    description: "Deep chemical bath, corrosion removal, board drying & micro-component diagnostic restoration.",
    popular: false,
  },
  {
    id: "serv-logic",
    name: "Logic Board Micro-Soldering Repair",
    category: "Laptop",
    price: 199,
    duration: "24-48 hrs",
    warranty: "6 Months Warranty",
    ecoSavingsKg: 12.4,
    description: "Component-level micro-soldering, IC chip replacement, and power rail diagnostics.",
    popular: true,
  },
  {
    id: "serv-mac-battery",
    name: "MacBook / Laptop Battery Swap",
    category: "Laptop",
    price: 149,
    duration: "1-2 hrs",
    warranty: "1 Year Warranty",
    ecoSavingsKg: 6.8,
    description: "Complete battery module replacement with thermal paste application & fan dusting.",
    popular: false,
  },
  {
    id: "serv-port",
    name: "Type-C / Lightning Port Repair",
    category: "Smartphone",
    price: 59,
    duration: "30-45 mins",
    warranty: "1 Year Warranty",
    ecoSavingsKg: 1.5,
    description: "Flex cable & charging connector replacement with high-current power delivery testing.",
    popular: false,
  },
];

export const MOCK_REPAIR_SHOPS: RepairShop[] = [
  {
    id: "shop-1",
    name: "iFix Green Labs & Repair Hub",
    logo: "🌿",
    tagline: "Certified OEM Parts & Zero-Landfill Guarantee",
    rating: 4.9,
    reviewCount: 342,
    aiTrustScore: 98,
    circularContributionScore: 97,
    distanceMiles: 1.2,
    estimatedTime: "1-2 hrs",
    address: "742 Market Street, Suite 400",
    city: "San Francisco",
    state: "CA",
    zipCode: "94103",
    lat: 37.7882,
    lng: -122.4024,
    phone: "(415) 890-3412",
    email: "support@ifixgreenlabs.com",
    website: "https://ifixgreenlabs.example.com",
    businessHours: "Mon-Sat: 9:00 AM - 7:00 PM",
    warrantyPeriod: "1 Year OEM Warranty",
    pickupAvailable: true,
    pickupDetails: "Free Doorstep Express Courier Pickup & Delivery (Within 5 Miles)",
    verifiedPartner: true,
    oemPartsCertified: true,
    bio: "iFix Green Labs is San Francisco's premier eco-certified electronics restoration center. We specialize in precision micro-soldering, original display replacements, and e-waste circular recovery.",
    badges: ["Top AI Match", "OEM Partner", "100% Eco Recycled", "Express 1-Hr"],
    environmentalMetrics: {
      eWastePreventedKg: 1420,
      co2EmissionsSavedKg: 8900,
      preciousMetalsRecoveredGrams: 340,
      circularRank: "Top 1% Eco Champion",
    },
    services: COMMON_REPAIR_CATALOG,
    reviews: [
      {
        id: "rev-1",
        author: "Sarah Jenkins",
        avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
        rating: 5,
        date: "2 days ago",
        device: "iPhone 14 Pro",
        repairType: "OLED Screen & Glass Replacement",
        content: "Extremely fast service! They picked up my phone at 10 AM and returned it pristine by 1 PM. Saved me $700 compared to buying a new device.",
        verifiedPurchase: true,
        shopResponse: {
          date: "1 day ago",
          content: "Thank you Sarah! Keeping devices out of landfills is our mission. Enjoy your fresh OLED display!",
        },
      },
      {
        id: "rev-2",
        author: "David Chen",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150",
        rating: 5,
        date: "1 week ago",
        device: "MacBook Pro M1 16-inch",
        repairType: "Logic Board Micro-Soldering Repair",
        content: "Apple Store told me I needed a full motherboard replacement for $1,200. iFix Green repaired the shorted capacitor for $199! Phenomenal tech knowledge.",
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: "shop-2",
    name: "Silicon MicroFix Electronics",
    logo: "🔬",
    tagline: "Component-Level Repair & Board Diagnostics",
    rating: 4.8,
    reviewCount: 218,
    aiTrustScore: 95,
    circularContributionScore: 94,
    distanceMiles: 2.5,
    estimatedTime: "2-4 hrs",
    address: "1280 Mission St",
    city: "San Francisco",
    state: "CA",
    zipCode: "94103",
    lat: 37.7785,
    lng: -122.415,
    phone: "(415) 554-1029",
    email: "service@siliconmicrofix.com",
    website: "https://siliconmicrofix.example.com",
    businessHours: "Mon-Fri: 8:30 AM - 6:30 PM",
    warrantyPeriod: "180 Days Warranty",
    pickupAvailable: true,
    pickupDetails: "Courier Pickup Available ($10 or Free for orders over $150)",
    verifiedPartner: true,
    oemPartsCertified: true,
    bio: "Micro-soldering pioneers specializing in water damage resuscitation, logic board recovery, and server hardware repairs.",
    badges: ["Micro-soldering Specialist", "Same Day Service", "Verified Partner"],
    environmentalMetrics: {
      eWastePreventedKg: 980,
      co2EmissionsSavedKg: 6200,
      preciousMetalsRecoveredGrams: 210,
      circularRank: "Top 5% Eco Leader",
    },
    services: COMMON_REPAIR_CATALOG,
    reviews: [
      {
        id: "rev-3",
        author: "Elena Rostova",
        avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
        rating: 5,
        date: "3 weeks ago",
        device: "iPad Pro 12.9",
        repairType: "Type-C Port Repair",
        content: "Fixed my loose charging port within 40 minutes. Clean environment and friendly staff.",
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: "shop-3",
    name: "EcoCell Renewal & Battery Depot",
    logo: "⚡",
    tagline: "Battery Health Optimization & Screen Specialists",
    rating: 4.9,
    reviewCount: 410,
    aiTrustScore: 96,
    circularContributionScore: 98,
    distanceMiles: 3.8,
    estimatedTime: "30-60 mins",
    address: "310 Valencia Street",
    city: "San Francisco",
    state: "CA",
    zipCode: "94103",
    lat: 37.7689,
    lng: -122.4223,
    phone: "(415) 901-7782",
    email: "contact@ecocellrenewal.com",
    website: "https://ecocellrenewal.example.com",
    businessHours: "Mon-Sun: 9:00 AM - 8:00 PM",
    warrantyPeriod: "1 Year Battery & Screen Warranty",
    pickupAvailable: true,
    pickupDetails: "Doorstep Battery Replacement Van (We Come To You)",
    verifiedPartner: true,
    oemPartsCertified: false,
    bio: "We bring mobile repair to your front door or office! Specializing in rapid battery swaps and screen replacements with 100% battery recycling compliance.",
    badges: ["Mobile Van Repair", "Eco Battery Recycler", "Fast 30-Min"],
    environmentalMetrics: {
      eWastePreventedKg: 2150,
      co2EmissionsSavedKg: 13400,
      preciousMetalsRecoveredGrams: 510,
      circularRank: "Top 1% Battery Saver",
    },
    services: COMMON_REPAIR_CATALOG,
    reviews: [
      {
        id: "rev-4",
        author: "Marcus Vance",
        avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150",
        rating: 5,
        date: "5 days ago",
        device: "Samsung Galaxy S22 Ultra",
        repairType: "High-Capacity Battery Replacement",
        content: "The mobile van service arrived at my workplace. Battery replaced in 25 minutes flat while I worked inside!",
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: "shop-4",
    name: "ReviveTech Gadget Clinic",
    logo: "🛠️",
    tagline: "Multi-Brand Console, Laptop & Smartphone Repairs",
    rating: 4.7,
    reviewCount: 184,
    aiTrustScore: 91,
    circularContributionScore: 90,
    distanceMiles: 4.5,
    estimatedTime: "2-5 hrs",
    address: "1850 Haight Street",
    city: "San Francisco",
    state: "CA",
    zipCode: "94117",
    lat: 37.7698,
    lng: -122.4512,
    phone: "(415) 387-9921",
    email: "hello@revivetechclinic.com",
    website: "https://revivetech.example.com",
    businessHours: "Tue-Sat: 10:00 AM - 6:00 PM",
    warrantyPeriod: "6 Months Warranty",
    pickupAvailable: false,
    pickupDetails: "In-store Walk-ins & Mail-in Only",
    verifiedPartner: true,
    oemPartsCertified: true,
    bio: "Community-driven repair shop dedicated to extending device lifecycles. We fix everything from vintage iPods and Nintendo Switches to latest flagship phones.",
    badges: ["Console Specialist", "Student Discount", "Walk-in Welcome"],
    environmentalMetrics: {
      eWastePreventedKg: 740,
      co2EmissionsSavedKg: 4900,
      preciousMetalsRecoveredGrams: 180,
      circularRank: "Top 10% Community Eco Hero",
    },
    services: COMMON_REPAIR_CATALOG,
    reviews: [
      {
        id: "rev-5",
        author: "Chloe Bennett",
        avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150",
        rating: 4,
        date: "2 weeks ago",
        device: "PlayStation 5",
        repairType: "HDMI Port Replacement",
        content: "Super friendly guys. Fixed the bent HDMI port on my PS5 within a day. Price was reasonable.",
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: "shop-5",
    name: "Apex Micro Electronics Restoration",
    logo: "⚡",
    tagline: "Industrial & Enterprise Device Refurbishment",
    rating: 4.6,
    reviewCount: 95,
    aiTrustScore: 89,
    circularContributionScore: 92,
    distanceMiles: 5.8,
    estimatedTime: "24-48 hrs",
    address: "2400 3rd Street",
    city: "San Francisco",
    state: "CA",
    zipCode: "94107",
    lat: 37.7601,
    lng: -122.3881,
    phone: "(415) 641-8833",
    email: "apex@apexrepair.example.com",
    website: "https://apexrepair.example.com",
    businessHours: "Mon-Fri: 9:00 AM - 5:00 PM",
    warrantyPeriod: "1 Year Enterprise Warranty",
    pickupAvailable: true,
    pickupDetails: "Scheduled Bulk & Corporate Courier Pickup",
    verifiedPartner: true,
    oemPartsCertified: true,
    bio: "Enterprise-grade refurbishment lab providing certified micro-soldering, data recovery, and circular hardware lifecycle management for businesses and individuals.",
    badges: ["Enterprise Grade", "Data Recovery", "ISO Certified"],
    environmentalMetrics: {
      eWastePreventedKg: 3400,
      co2EmissionsSavedKg: 21000,
      preciousMetalsRecoveredGrams: 890,
      circularRank: "Enterprise Circular Leader",
    },
    services: COMMON_REPAIR_CATALOG,
    reviews: [
      {
        id: "rev-6",
        author: "Robert Sterling",
        avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150",
        rating: 5,
        date: "1 month ago",
        device: "Dell XPS 15",
        repairType: "Ultrasonic Water Damage Decontamination",
        content: "Recovered all critical project data after coffee spill. Unbelievable service!",
        verifiedPurchase: true,
      },
    ],
  },
];

export const INITIAL_BOOKING_DATA: BookingRequest = {
  id: "book-101",
  shopId: "shop-1",
  shopName: "iFix Green Labs & Repair Hub",
  deviceCategory: "Smartphone",
  deviceBrand: "Apple",
  deviceModel: "iPhone 14 Pro",
  issueType: "OLED Screen & Glass Replacement",
  issueDescription: "Cracked glass on lower right corner. Touchscreen is responsive.",
  date: "2026-08-08",
  timeSlot: "10:30 AM - 11:30 AM",
  userFullName: "Alex Mercer",
  userEmail: "alex.mercer@example.com",
  userPhone: "+1 (555) 234-5678",
  pickupRequested: true,
  pickupAddress: "123 Green St, Apt 4B, San Francisco, CA 94102",
  userNotes: "Please call when courier is 15 minutes away.",
  estimatedCost: 129,
  confirmationId: "RIX-88421",
  status: "Confirmed",
  createdAt: "2026-08-05T14:20:00Z",
};

export const REPAIR_TIMELINE_STAGES = [
  {
    step: 1,
    title: "Appointment Booked & Confirmed",
    description: "Shop notified. Courier dispatched or walk-in slot reserved.",
    completed: true,
    time: "Today, 02:20 PM",
  },
  {
    step: 2,
    title: "AI & Visual Diagnostic Inspection",
    description: "Detailed component check, battery health audit & serial verification.",
    completed: true,
    time: "Today, 03:00 PM",
  },
  {
    step: 3,
    title: "Precision Micro-Repair & OEM Parts",
    description: "Display replacement, true-tone calibration & water seal re-application.",
    completed: false,
    current: true,
    time: "In Progress (Est. 45 mins)",
  },
  {
    step: 4,
    title: "Quality Control & Circular Score Audit",
    description: "Functionality testing, display touch matrix check & e-waste logging.",
    completed: false,
    time: "Pending Step 3",
  },
  {
    step: 5,
    title: "Ready for Pickup / Courier Return",
    description: "Device sanitized, packaged in recycled eco-box & ready for handoff.",
    completed: false,
    time: "Est. 05:30 PM Today",
  },
];

export const MOCK_AI_RESPONSES: Record<string, string> = {
  "screen repair worth it": "Yes! Repairing your OLED screen costs around $129, saving you over $750 compared to buying a replacement phone. It also prevents approximately 3.2 kg of e-waste and saves 45 kg of CO2 emissions.",
  "fastest repair shop": "iFix Green Labs offers 45-60 minute express screen and battery repairs, with doorstep pickup included!",
  "warranty coverage": "All verified shops on RevalueIQ offer a minimum of 180 Days to 1 Year warranty on genuine parts and labor.",
  "what is trust score": "The AI Trust Score (0-100) measures customer satisfaction, OEM parts authenticity, technician certification level, transparent pricing history, and warranty claim rate.",
  "pickup option": "Shops like iFix Green Labs and EcoCell Renewal offer free or low-cost doorstep courier pickup within a 5-mile radius.",
};
